"""KKI build-phase foundation package."""

from .data_models import (
    CoreState,
    EvidenceRecord,
    PersistenceRecord,
    TransferEnvelope,
    core_state_for_runtime,
    transfer_envelope_for_state,
)
from .message_protocols import (
    DeliveryGuarantee,
    DeliveryMode,
    EventEnvelope,
    MessageEnvelope,
    MessageKind,
    ProtocolContext,
    command_message,
    event_message,
    evidence_message,
    protocol_context,
    transfer_message,
)
from .module_boundaries import (
    ModuleBoundary,
    ModuleBoundaryName,
    module_boundaries,
    module_boundary,
    module_dependency_graph,
)
from .runtime_dna import (
    RuntimeDNA,
    RuntimeHooks,
    RuntimeIdentity,
    RuntimeStage,
    RuntimeThresholds,
    runtime_dna_for_profile,
    runtime_dna_from_env,
)
from .security import (
    ActionName,
    AuthorizationDecision,
    AuthorizationIdentity,
    DelegationGrant,
    IdentityKind,
    OperatingMode,
    PermissionRule,
    RoleName,
    TrustLevel,
    authorize_action,
    permission_catalog,
    role_permissions,
)

__all__ = [
    "CoreState",
    "DeliveryGuarantee",
    "DeliveryMode",
    "EvidenceRecord",
    "EventEnvelope",
    "MessageEnvelope",
    "MessageKind",
    "ActionName",
    "AuthorizationDecision",
    "AuthorizationIdentity",
    "DelegationGrant",
    "IdentityKind",
    "ModuleBoundary",
    "ModuleBoundaryName",
    "OperatingMode",
    "PermissionRule",
    "PersistenceRecord",
    "ProtocolContext",
    "RoleName",
    "RuntimeDNA",
    "RuntimeHooks",
    "RuntimeIdentity",
    "RuntimeStage",
    "RuntimeThresholds",
    "TransferEnvelope",
    "TrustLevel",
    "authorize_action",
    "command_message",
    "core_state_for_runtime",
    "event_message",
    "evidence_message",
    "module_boundaries",
    "module_boundary",
    "module_dependency_graph",
    "permission_catalog",
    "protocol_context",
    "role_permissions",
    "runtime_dna_for_profile",
    "runtime_dna_from_env",
    "transfer_message",
    "transfer_envelope_for_state",
]
